# Generated by Django 5.2.5 on 2026-03-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('img_path', models.CharField(max_length=500)),
                ('three_d_models', models.JSONField(default=list)),
                ('path', models.JSONField(default=list)),
            ],
        ),
    ]
